[basic/signing-simple] [INIT INFO] Fixture configuration updated
[basic/signing-simple] [INIT INFO] Scenario 'signing-simple' specified but no services directory found at /App/scenario-overrides/services
[basic/signing-simple] [INFO] ### Request: Instances.PostSimplified - User: SystemUser/950474084/d111dbab-d619-4f15-bf29-58fe570a9ae6, AuthLevel: 3, AuthMethod: maskinporten
[basic/signing-simple] [INFO] IInstantiationValidator.Validate
[basic/signing-simple] [INFO] IProcessTaskStart.Start
[basic/signing-simple] [INFO] IInstantiationProcessor.DataCreation
[basic/signing-simple] [INFO] ### Response: Instances.PostSimplified - CreatedResult, StatusCode: 201
[basic/signing-simple] [INFO] ### Request: Process.NextElement - User: SystemUser/950474084/d111dbab-d619-4f15-bf29-58fe570a9ae6, AuthLevel: 3, AuthMethod: maskinporten
[basic/signing-simple] [INFO] IValidator.Validate
[basic/signing-simple] [INFO] ITaskValidator.ValidateTask
[basic/signing-simple] [INFO] IDataElementValidator.ValidateDataElement
[basic/signing-simple] [INFO] IFormDataValidator.ValidateFormData
fail: Altinn.App.Core.Features.Signing.Services.SigningService[0]
      Failed to create signee contexts for 1 unmatched documents for task Task_1.
      System.ArgumentException: Could not find party for person or organization. A valid SSN or OrgNr must be provided.
         at Altinn.App.Core.Features.Signing.Models.Signee.From(String ssn, String orgNr, Nullable`1 systemId, Func`2 lookupParty) in /_/src/Altinn.App.Core/Features/Signing/Models/SigneeContext.cs:line 140
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextFromSignDocument(String taskId, SignDocument signDocument) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 292
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextsForUnmatchedDocuments(String taskId, List`1 unmatchedSignDocuments) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 263
fail: Altinn.App.Core.Internal.Validation.ValidationService[0]
      Error while running validator Altinn.App.Core.Features.Validation.Default.SigningTaskValidator-* for task Task_1 on instance 500700/629e01b6-7965-40df-bd51-d8162c004cce
      System.ArgumentException: Could not find party for person or organization. A valid SSN or OrgNr must be provided.
         at Altinn.App.Core.Features.Signing.Models.Signee.From(String ssn, String orgNr, Nullable`1 systemId, Func`2 lookupParty) in /_/src/Altinn.App.Core/Features/Signing/Models/SigneeContext.cs:line 140
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextFromSignDocument(String taskId, SignDocument signDocument) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 292
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextsForUnmatchedDocuments(String taskId, List`1 unmatchedSignDocuments) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 263
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.SynchronizeSigneeContextsWithSignDocuments(String taskId, List`1 signeeContexts, List`1 signDocuments, CancellationToken ct) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 136
         at Altinn.App.Core.Features.Signing.Services.SigningService.GetSigneeContexts(IInstanceDataAccessor instanceDataAccessor, AltinnSignatureConfiguration signatureConfiguration, CancellationToken ct) in /_/src/Altinn.App.Core/Features/Signing/Services/SigningService.cs:line 182
         at Altinn.App.Core.Features.Validation.Default.SigningTaskValidator.Validate(IInstanceDataAccessor dataAccessor, String taskId, String language) in /_/src/Altinn.App.Core/Features/Validation/Default/SigningTaskValidator.cs:line 92
         at Altinn.App.Core.Internal.Validation.ValidationService.<>c__DisplayClass5_0.<<ValidateInstanceAtTask>b__3>d.MoveNext() in /_/src/Altinn.App.Core/Internal/Validation/ValidationService.cs:line 67
fail: Altinn.App.Api.Controllers.ProcessController[0]
      Process next failed.
      System.ArgumentException: Could not find party for person or organization. A valid SSN or OrgNr must be provided.
         at Altinn.App.Core.Features.Signing.Models.Signee.From(String ssn, String orgNr, Nullable`1 systemId, Func`2 lookupParty) in /_/src/Altinn.App.Core/Features/Signing/Models/SigneeContext.cs:line 140
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextFromSignDocument(String taskId, SignDocument signDocument) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 292
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.CreateSigneeContextsForUnmatchedDocuments(String taskId, List`1 unmatchedSignDocuments) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 263
         at Altinn.App.Core.Features.Signing.Services.SignDocumentManager.SynchronizeSigneeContextsWithSignDocuments(String taskId, List`1 signeeContexts, List`1 signDocuments, CancellationToken ct) in /_/src/Altinn.App.Core/Features/Signing/Services/SignDocumentManager.cs:line 136
         at Altinn.App.Core.Features.Signing.Services.SigningService.GetSigneeContexts(IInstanceDataAccessor instanceDataAccessor, AltinnSignatureConfiguration signatureConfiguration, CancellationToken ct) in /_/src/Altinn.App.Core/Features/Signing/Services/SigningService.cs:line 182
         at Altinn.App.Core.Features.Validation.Default.SigningTaskValidator.Validate(IInstanceDataAccessor dataAccessor, String taskId, String language) in /_/src/Altinn.App.Core/Features/Validation/Default/SigningTaskValidator.cs:line 92
         at Altinn.App.Core.Internal.Validation.ValidationService.<>c__DisplayClass5_0.<<ValidateInstanceAtTask>b__3>d.MoveNext() in /_/src/Altinn.App.Core/Internal/Validation/ValidationService.cs:line 67
      --- End of stack trace from previous location ---
         at Altinn.App.Core.Internal.Validation.ValidationService.ValidateInstanceAtTask(IInstanceDataAccessor dataAccessor, String taskId, List`1 ignoredValidators, Nullable`1 onlyIncrementalValidators, String language) in /_/src/Altinn.App.Core/Internal/Validation/ValidationService.cs:line 92
         at Altinn.App.Api.Controllers.ProcessController.GetValidationProblemDetails(Instance instance, String currentTaskId, String language) in /_/src/Altinn.App.Api/Controllers/ProcessController.cs:line 249
         at Altinn.App.Api.Controllers.ProcessController.NextElement(String org, String app, Int32 instanceOwnerPartyId, Guid instanceGuid, CancellationToken ct, String elementId, String language, ProcessNext processNext) in /_/src/Altinn.App.Api/Controllers/ProcessController.cs:line 396
[basic/signing-simple] [INFO] ### Response: Process.NextElement - ObjectResult, StatusCode: 500
[basic/signing-simple] [INFO] ### Request: Instances.Get - User: SystemUser/950474084/d111dbab-d619-4f15-bf29-58fe570a9ae6, AuthLevel: 3, AuthMethod: maskinporten
[basic/signing-simple] [INFO] ### Response: Instances.Get - OkObjectResult, StatusCode: 200
[basic/signing-simple] [INFO] ### Request: ApplicationMetadata.GetAction - User: None/none, AuthLevel: 0, AuthMethod: none
[basic/signing-simple] [INFO] ### Response: ApplicationMetadata.GetAction - OkObjectResult, StatusCode: 200
[basic/signing-simple] [INFO] ### Request: Data.Get - User: SystemUser/950474084/d111dbab-d619-4f15-bf29-58fe570a9ae6, AuthLevel: 3, AuthMethod: maskinporten
[basic/signing-simple] [INFO] IDataProcessor.ProcessDataRead
[basic/signing-simple] [INFO] ### Response: Data.Get - OkObjectResult, StatusCode: 200
[basic/signing-simple] [INFO] ### Request: Data.Get - User: SystemUser/950474084/d111dbab-d619-4f15-bf29-58fe570a9ae6, AuthLevel: 3, AuthMethod: maskinporten
[basic/signing-simple] [INFO] ### Response: Data.Get - FileStreamResult, StatusCode: 